os: osx
osx_image: xcode9.4

jobs:
  include:
    - env:
        - PYTHON_VERSION=3.8.0

install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda create -q -n test-env python=$PYTHON_VERSION

script:
  - which python
  - python --version
  # - python -c "import sklearn"
