os: osx
osx_image: xcode9.4
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  # - pip install --pre --upgrade -f artifact scikit-learn
  - pip install scikit-learn==0.24.0

script:
  - python -c "import sklearn"
