os: osx
osx_image: xcode9.4

addons:
  homebrew:
    packages:
      - pyenv

jobs:
  include:
    - env:
        - PYTHON_VERSION=3.8.0

install:
  # - pip install --pre --upgrade -f artifact scikit-learn
  - pyenv install $PYTHON_VERSION
  # - pip install scikit-learn==0.24.0

script:
  - pyenv init
  - pyenv shell $PYTHON_VERSION
  - which python
  - python --version
  # - python -c "import sklearn"
