os: osx
osx_image: xcode9.4 # this uses osx 10.13

jobs:
  include:
    # - env:
    #     - PYTHON_VERSION=3.6
    # - env:
    #     - PYTHON_VERSION=3.7
    # - env:
    #     - PYTHON_VERSION=3.8
    - env:
        - PYTHON_VERSION=3.9

install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda create -q -n test-env python=$PYTHON_VERSION -y
  - conda activate test-env
  # - pip install --pre -f artifact scikit-learn
  - pip install scikit-learn==0.24.0

script:
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda activate test-env
  - which python
  - python --version
  - python -c "import sklearn"
